"use client";

import { useRouter } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { useAuth } from "@/lib/useAuth";
import { signOut } from "@/lib/auth";
import { isCloud } from "@/lib/store";
import { IconLogout, IconLink, IconSparkle } from "@/components/icons";

export default function SettingsPage() {
  const router = useRouter();
  const { user } = useAuth();

  async function handleSignOut() {
    await signOut();
    router.replace("/login");
  }

  return (
    <AppShell>
      <div className="mx-auto max-w-2xl px-5 py-8 sm:px-8">
        <h1 className="text-2xl font-semibold tracking-tight">Settings</h1>
        <p className="mt-1 text-sm text-[var(--text-dim)]">
          Manage your account and workspace.
        </p>

        {/* Account */}
        <div className="card mt-6 p-5">
          <h2 className="text-sm font-semibold">Account</h2>
          <div className="mt-4 flex items-center gap-3">
            <span className="grid h-12 w-12 place-items-center rounded-full brand-gradient text-sm font-bold text-white">
              {(user?.email ?? "ME").slice(0, 2).toUpperCase()}
            </span>
            <div className="min-w-0">
              <div className="truncate font-medium">{user?.email ?? "Local user"}</div>
              <div className="text-xs text-[var(--text-faint)]">Signed in</div>
            </div>
          </div>
          <button onClick={handleSignOut} className="btn btn-danger mt-5">
            <IconLogout width={18} height={18} />
            Sign out
          </button>
        </div>

        {/* Workspace */}
        <div className="card mt-4 p-5">
          <h2 className="text-sm font-semibold">Workspace</h2>
          <div className="mt-3 flex items-center gap-2 text-sm">
            <IconLink width={16} height={16} className="text-[var(--success)]" />
            <span className="text-[var(--text-dim)]">
              {isCloud()
                ? "Cloud — recordings sync via Supabase; share links work anywhere."
                : "Local — recordings stored in this browser only."}
            </span>
          </div>
        </div>

        {/* AI */}
        <div className="card mt-4 p-5">
          <h2 className="flex items-center gap-2 text-sm font-semibold">
            <IconSparkle width={15} height={15} className="text-[var(--brand-2)]" />
            AI summaries
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-[var(--text-dim)]">
            Auto title, summary, and chapters are generated by Claude on the watch
            page. They require an <code className="text-[var(--text)]">ANTHROPIC_API_KEY</code> in
            the server environment.
          </p>
        </div>
      </div>
    </AppShell>
  );
}
